---
- hosts: all
  become: yes
  tasks:

  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat" 

  - name: install tree  
    apt:
      name: tree
      state: present
    when: ansible_os_family=="Debian"

  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat" 
  
  - name: start tree    
    service:
      name: tree
      state: started
    when: ansible_os_family=="Debian"

 
    