---
- hosts: all
  become: yes
  tasks:

  - name: install httpd
    yum:
      name: "{{mywebpkgonubuntu}}"
      state: present
    when: ansible_os_family=="RedHat" 

  - name: install apache2
    yum: 
      name: "{{mywebpkgonubuntu}}"
      state: latest
    when: ansible_os_family=="Debian"

  - name: start httpd
    service:
      name: "{{mywebpkgonredhat}}"
      state: started
    when: ansible_os_family=="RedHat" 

  - name: restart webserver  
    service:
      name: "{{mywebpkgonubuntu}}"
      state: restarted
    when: ansible_os_family=="Debian"    
  

 
    