---
- hosts: all
  become: yes
  tasks:

  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat" 

  - name: intall httpd   
    apt:
      name: httpd
      state: present
    when: ansible_os_family=="Debian"

  - name: start httpd
    service:
      name: httpd
      state: started
     
 
    