---
- hosts: all
  become: yes
  tasks:
  - include_tasks: myfile.yml   

  - name: install httpd
    yum:
      name: "{{mywebpkgonredhat}}"
      state: present
    when: ansible_os_family=="RedHat" 
    tags: myhttpd

  - name: install apache2
    apt: 
      name: "{{mywebpkgonubuntu}}"
      state: latest
    when: ansible_os_family=="Debian"
    tags: myapache2

  - name: start httpd
    service:
      name: "{{mywebpkgonredhat}}"
      state: restarted
    when: ansible_os_family=="RedHat" 

  - name: crete directory
    file:
      path: /home/swapnil/mydir1
      state: directory

  - name: copy file from master to node server
    copy: 
      src: /home/swapnil/mydemo2file
      dest: /home/mydemo2file 
    when: ansible_os_family=="RedHat"
    tags: mydir1


  handlers:
  - name: restart webserver  
    service:
      name: "{{mywebpkgonubuntu}}"
      state: restarted
    when: ansible_os_family=="Debian"

   

  

 
    